version: '3.8'
services:

  fluentd:
    build: ./docker
    image: anti1346/fluentd:latest
    restart: unless-stopped
    container_name: fluentd
    hostname: fluentd
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
      - ./docker/config/fluent.conf:/fluentd/etc/fluent.conf
      - ./fluentd_data/log:/fluentd/log
    network_mode: host
    # ports:
    #   - "8888:8888"
    #   - "24224:24224"
    #   - "24224:24224/udp"
